apiVersion: v1
kind: Service
metadata:
  name: hair-product-frontend
  labels:
    env: prod
    owner: sheriff
spec:
  selector:
    app: hair-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
