apiVersion: v1
kind: Pod
metadata:
  name: attack-pod-root
  labels:
    app: attack-test
    owner: sheriff
spec:
  containers:
  - name: attacker
    image: alpine
    securityContext:
      privileged: true
    command: ["sh", "-c", "whoami"]
